select * from cars;
select * from salespersons;
select * from sales;


--  5. What is the total revenue generated by each car type?
select c.type, sum(c.cost_$)
from cars c
join sales s
on c.car_id = s.car_id
group by c.type;