select * from cars;
select * from salespersons;
select * from sales;

-- 7. What is the total revenue generated by the sales of hatchback cars? 
select c.style, sum(c.cost_$) as revenue_by_hatchback_cars
from cars c
join sales s
on c.car_id = s.car_id
group by c.style
having c.style = 'Hatchback';