select * from cars;
select * from salespersons;
select * from sales
where year(purchase_date) = 2022 and car_id in(5,3);

select c.style, sum(c.cost_$) 
from cars c
join sales s  
on c.car_id = s.car_id
where year(purchase_date) = 2022 and c.style = 'SUV'
group by c.style;

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?

select c.style, sum(c.cost_$) as revenue_by_SUV_cars_in_2022 
from cars c
join sales s
on c.car_id = s.car_id
where year(s.purchase_date) = 2022
group by c.style
having c.style = 'SUV';

